import Student
import Teacher
import Committee

student1 = Student.Student("Sonali", 16, "A+", "S123", "R18", "10th class", "Mrs. Sharma", "9876543210")
print("Student Name:",student1.get_name())
print("Student Age:", student1.get_age())   
print("Student Grade:",student1.get_grade())
print("Student ID:", student1.get_id())
print("Student Roll Number:", student1.get_roll_number())
print("Student class:", student1.get_class_name())
print("Student parent Name:", student1.get_parent_name())
print("Student parent Contact Number:", student1.get_contact())



student2 = Student.Student("Madhuri", 17, "A", "S124", "R19", "11th class", "Mr. Verma", "9876543210")
print("Student Name:", student2.get_name())
print("Student Age:", student2.get_age())
print("Student Grade:", student2.get_grade())
print("Student ID:", student2.get_id())
print("Student Roll Number:", student2.get_roll_number())
print("Student class:", student2.get_class_name())
print("Student parent Name:", student2.get_parent_name())
print("Student parent Contact Number:", student2.get_contact())

teacher1 = Teacher.Teacher("Mr. Sharma", 40, "Mathematics", "T001", "10th class","50000", "15 years", "M.Sc. in Mathematics", "9876543210")
print("Teacher Name:", teacher1.get_name())
print("Teacher Age:", teacher1.get_age())
print("Teacher Subject:", teacher1.get_subject())
print("Teacher ID:", teacher1.get_id())
print("Teacher class:", teacher1.get_class())
print("Teacher Salary:", teacher1.get_salary())
print("Teacher Experience:", teacher1.get_experience())
print("Teacher Qualification:", teacher1.get_qualification())
print("Teacher Contact Number:", teacher1.get_contact())

teacher2 = Teacher.Teacher("Ms. Verma", 35, "Science", "T002", "9th class"," 45000", "10 years", "M.Sc. in Science", "9876543210")
print("Teacher Name:", teacher2.get_name())
print("Teacher Age:", teacher2.get_age())
print("Teacher Subject:", teacher2.get_subject())
print("Teacher ID:", teacher2.get_id())
print("Teacher class:", teacher2.get_class())
print("Teacher Salary:", teacher2.get_salary())
print("Teacher Experience:", teacher2.get_experience())
print("Teacher Qualification:", teacher2.get_qualification())
print("Teacher Contact Number:", teacher2.get_contact())

Committee1 = Committee.Committee("Mr. Singh", 45, "Principal", "C001", "20 years", "M.Ed.", "60000", "Administration Department", "9876543210")
print("Committee Member Name:", Committee1.get_name())
print("Committee Member Age:", Committee1.get_age())
print("Committee Member Position:", Committee1.get_position())
print("Committee Member ID:", Committee1.get_id())
print("Committee Member Experience:", Committee1.get_experience())
print("Committee Member Qualification:", Committee1.get_qualification())
print("Committee Member Salary:", Committee1.get_salary())
print("Committee Member Department:", Committee1.get_department())
print("Committee Member Contact Number:", Committee1.get_contact())

committee2 = Committee.Committee("Ms. Gupta", 38, "Vice Principal", "C002", "15 years", "M.Ed.", "50000", "Science Department", "9876543210")
print("Committee Member Name:", committee2.get_name())
print("Committee Member Age:", committee2.get_age())
print("Committee Member Position:", committee2.get_position())
print("Committee Member ID:", committee2.get_id())
print("Committee Member Experience:", committee2.get_experience())
print("Committee Member Qualification:", committee2.get_qualification())
print("Committee Member Salary:", committee2.get_salary())
print("Committee Member Department:", committee2.get_department())
print("Committee Member Contact Number:", committee2.get_contact())